import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:app_clinica_estetica/core/data/models/pacote_template_model.dart';
import 'package:app_clinica_estetica/core/data/models/professional_model.dart';

import 'package:app_clinica_estetica/core/data/repositories/supabase_professional_repository.dart';
import 'package:app_clinica_estetica/core/data/repositories/supabase_package_repository.dart';
import 'package:app_clinica_estetica/core/data/models/pacote_contratado_model.dart';
import 'package:app_clinica_estetica/core/theme/app_colors.dart';

class PacoteConfirmacaoPage extends StatefulWidget {
  final PacoteTemplateModel pacote;

  const PacoteConfirmacaoPage({super.key, required this.pacote});

  @override
  State<PacoteConfirmacaoPage> createState() => _PacoteConfirmacaoPageState();
}

class _PacoteConfirmacaoPageState extends State<PacoteConfirmacaoPage> {
  ProfessionalModel? selectedProfessional;
  List<ProfessionalModel> professionals = [];
  bool isLoading = true;
  bool isSaving = false;
  final _professionalRepository = SupabaseProfessionalRepository();
  final _packageRepository = SupabasePackageRepository(Supabase.instance.client);

  @override
  void initState() {
    super.initState();
    _loadProfessionals();
  }

  Future<void> _loadProfessionals() async {
    try {
      final results = await _professionalRepository.getProfessionalsByPackage(widget.pacote.id);
      if (mounted) {
        setState(() {
          professionals = results;
          isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro ao carregar profissionais: $e')),
        );
      }
    }
  }

  Future<void> _confirmarPacote() async {
    if (selectedProfessional == null) return;

    setState(() => isSaving = true);

    try {
      final user = Supabase.instance.client.auth.currentUser;
      if (user == null) throw Exception('Usuário não autenticado');

      final novoContrato = PacoteContratadoModel(
        id: '', // Will be generated by Supabase
        templateId: widget.pacote.id,
        clienteId: user.id,
        profissionalId: selectedProfessional!.id,
        valorPago: widget.pacote.isPromocao 
            ? widget.pacote.valorPromocional! 
            : widget.pacote.valorTotal,
        sessoesTotais: widget.pacote.quantidadeSessoes,
        sessoesRealizadas: 0,
        status: 'ativo',
        comissaoPercentual: widget.pacote.comissaoPercentual,
        criadoEm: DateTime.now(),
      );


      final contratoCriado = await _packageRepository.createContratado(novoContrato);

      if (mounted) {
        setState(() => isSaving = false);
        
        // Navega para a seleção da primeira sessão do novo pacote
        context.push('/pacote-sessao-selecao', extra: {
          'pacote': widget.pacote,
          'profissional': selectedProfessional,
          'contratoId': contratoCriado.id,
          'sessaoNumero': 1,
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => isSaving = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro ao confirmar pacote: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final primaryColor = AppColors.primary;
    final backgroundColor = AppColors.background;

    final String packageImage = widget.pacote.imagemUrl ?? 
        'https://images.unsplash.com/photo-1512290923902-8a9f81dc2069?auto=format&fit=crop&q=80&w=400';

    return Scaffold(
      backgroundColor: backgroundColor,
      body: SafeArea(
        child: Column(
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Align(
                    alignment: Alignment.centerLeft,
                    child: IconButton(
                      onPressed: () => context.pop(),
                      icon: Icon(
                        Icons.chevron_left,
                        color: primaryColor,
                        size: 24,
                      ),
                    ),
                  ),
                  Text(
                    'Confirmação de Pacote',
                    style: TextStyle(fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: primaryColor,
                    ),
                  ),
                ],
              ),
            ),

            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Column(
                  children: [
                    const SizedBox(height: 16),
                    // Main Package Card
                    Container(
                      width: double.infinity,
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(30),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.05),
                            blurRadius: 20,
                            offset: const Offset(0, 10),
                          ),
                        ],
                      ),
                      child: Column(
                        children: [
                          // Hero Image
                          ClipRRect(
                            borderRadius: const BorderRadius.vertical(
                              top: Radius.circular(30),
                            ),
                            child: Hero(
                              tag: 'package-image-${widget.pacote.id}',
                              child: packageImage.startsWith('http')
                                  ? Image.network(
                                      packageImage,
                                      height: 250,
                                      width: double.infinity,
                                      fit: BoxFit.cover,
                                      errorBuilder: (context, error, stackTrace) =>
                                          Container(
                                            height: 250,
                                            color: Colors.grey[100],
                                            child: const Icon(Icons.inventory_2, size: 40, color: Colors.grey),
                                          ),
                                    )
                                  : Image.asset(
                                      packageImage,
                                      height: 250,
                                      width: double.infinity,
                                      fit: BoxFit.cover,
                                    ),
                            ),
                          ),
                          
                          Padding(
                            padding: const EdgeInsets.symmetric(
                              vertical: 24,
                              horizontal: 16,
                            ),
                            child: Text(
                              widget.pacote.titulo,
                              textAlign: TextAlign.center,
                              style: TextStyle(fontFamily: 'Playfair Display', 
                                fontSize: 28,
                                fontWeight: FontWeight.bold,
                                color: primaryColor,
                                height: 1.2,
                              ),
                            ),
                          ),

                          // Detail Cards
                          _construirCardDetalhe(
                            icon: Icons.layers_outlined,
                            label: 'SESSÕES',
                            value: '${widget.pacote.quantidadeSessoes} Unidades',
                          ),
                          
                          const SizedBox(height: 12),
                          
                          _construirCardDetalhe(
                            icon: Icons.payments_outlined,
                            label: 'INVESTIMENTO TOTAL',
                            value: widget.pacote.isPromocao 
                                ? widget.pacote.formattedPromotionalPrice 
                                : widget.pacote.formattedPrice,
                            subtitle: widget.pacote.isPromocao 
                                ? 'De ${widget.pacote.formattedPrice}' 
                                : null,
                          ),
                          
                          const SizedBox(height: 24),
                          
                          Padding(
                            padding: const EdgeInsets.symmetric(horizontal: 24),
                            child: Align(
                              alignment: Alignment.centerLeft,
                              child: Text(
                                'ESCOLHA O PROFISSIONAL',
                                style: TextStyle(fontSize: 10,
                                  fontWeight: FontWeight.bold,
                                  letterSpacing: 1,
                                  color: Colors.black26,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(height: 12),
                          
                          if (isLoading)
                            const Padding(
                              padding: EdgeInsets.all(24),
                              child: CircularProgressIndicator(),
                            )
                          else if (professionals.isEmpty)
                            const Padding(
                              padding: EdgeInsets.all(24),
                              child: Text('Nenhum profissional disponível para este pacote.'),
                            )
                          else
                            Padding(
                              padding: const EdgeInsets.only(bottom: 24),
                              child: Column(
                                children: professionals.map((p) => _buildSelectableProfessionalCard(p)).toList(),
                              ),
                            ),

                          const Padding(
                            padding: EdgeInsets.symmetric(horizontal: 24),
                            child: Divider(color: Color(0xFFF0F0F0)),
                          ),

                          Padding(
                            padding: const EdgeInsets.all(24),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  'Total do Pacote',
                                  style: TextStyle(fontSize: 16,
                                    color: Colors.black54,
                                  ),
                                ),
                                Column(
                                  crossAxisAlignment: CrossAxisAlignment.end,
                                  children: [
                                    if (widget.pacote.isPromocao)
                                      Text(
                                        widget.pacote.formattedPrice,
                                        style: TextStyle(fontSize: 14,
                                          decoration: TextDecoration.lineThrough,
                                          color: Colors.black26,
                                        ),
                                      ),
                                    Text(
                                      widget.pacote.isPromocao 
                                          ? widget.pacote.formattedPromotionalPrice 
                                          : widget.pacote.formattedPrice,
                                      style: TextStyle(fontFamily: 'Playfair Display', 
                                        fontSize: 22,
                                        fontWeight: FontWeight.bold,
                                        color: widget.pacote.isPromocao ? AppColors.accent : primaryColor,
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 32),
                    Text(
                      '* O pagamento será realizado diretamente na clínica no dia da primeira sessão.',
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 12,
                        color: Colors.black45,
                        height: 1.5,
                      ),
                    ),
                    const SizedBox(height: 40),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: Container(
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
        decoration: const BoxDecoration(color: AppColors.background),
        child: ElevatedButton(
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryColor,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(15),
            ),
          ),
          onPressed: (selectedProfessional == null || isSaving)
              ? null
              : _confirmarPacote,
          child: isSaving
              ? const SizedBox(
                  height: 24,
                  width: 24,
                  child: CircularProgressIndicator(
                    color: Colors.white,
                    strokeWidth: 2,
                  ),
                )
              : const Text(
                  'Confirmar Agendamento',
                  style: TextStyle(fontSize: 16,
                    fontWeight: FontWeight.bold,
                    letterSpacing: 0.5,
                  ),
                ),
        ),
      ),
    );
  }

  Widget _construirCardDetalhe({
    required IconData icon,
    required String label,
    required String value,
    String? subtitle,
  }) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 24),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFF9F9F9),
        borderRadius: BorderRadius.circular(15),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: AppColors.primary.withOpacity(0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(icon, color: AppColors.primary, size: 20),
          ),
          const SizedBox(width: 16),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                label,
                style: TextStyle(fontSize: 10,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1,
                  color: Colors.black26,
                ),
              ),
              Text(
                value,
                style: TextStyle(fontSize: 14,
                  fontWeight: FontWeight.bold,
                  color: Colors.black87,
                ),
              ),
              if (subtitle != null)
                Text(
                  subtitle,
                  style: TextStyle(fontSize: 12,
                    color: Colors.black26,
                    decoration: TextDecoration.lineThrough,
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildSelectableProfessionalCard(ProfessionalModel p) {
    final isSelected = selectedProfessional?.id == p.id;
    final accentColor = AppColors.accent;

    return GestureDetector(
      onTap: () => setState(() => selectedProfessional = p),
      child: Container(
        margin: const EdgeInsets.symmetric(horizontal: 24, vertical: 6),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: const Color(0xFFF9F9F9),
          borderRadius: BorderRadius.circular(15),
          border: Border.all(
            color: isSelected ? accentColor : Colors.transparent,
            width: 2,
          ),
        ),
        child: Row(
          children: [
            CircleAvatar(
              radius: 20,
              backgroundImage: p.avatarUrl != null 
                  ? NetworkImage(p.avatarUrl!) 
                  : null,
              child: p.avatarUrl == null 
                  ? const Icon(Icons.person, size: 20) 
                  : null,
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'PROFISSIONAL',
                    style: TextStyle(fontSize: 10,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1,
                      color: Colors.black26,
                    ),
                  ),
                  Text(
                    p.nome,
                    style: TextStyle(fontSize: 14,
                      fontWeight: FontWeight.bold,
                      color: isSelected ? AppColors.primary : Colors.black87,
                    ),
                  ),
                  Text(
                    (p.cargo ?? 'Especialista').toUpperCase(),
                    style: TextStyle(fontSize: 10,
                      fontWeight: FontWeight.bold,
                      color: AppColors.accent,
                      letterSpacing: 0.5,
                    ),
                  ),
                ],
              ),
            ),
            if (isSelected)
              Icon(Icons.check_circle, color: accentColor, size: 20)
            else
              Icon(Icons.circle_outlined, color: Colors.black12, size: 20),
          ],
        ),
      ),
    );
  }
}

