import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:app_clinica_estetica/core/data/models/promotion_model.dart';
import 'package:app_clinica_estetica/core/data/models/service_model.dart';
import 'package:app_clinica_estetica/core/data/repositories/supabase_promotion_repository.dart';
import 'package:app_clinica_estetica/core/data/repositories/supabase_service_repository.dart';
import 'package:app_clinica_estetica/core/data/repositories/supabase_package_repository.dart';
import 'package:app_clinica_estetica/core/data/models/pacote_template_model.dart';
import 'package:app_clinica_estetica/core/data/repositories/dashboard_repository.dart';
import 'package:app_clinica_estetica/core/theme/app_colors.dart';
import 'package:app_clinica_estetica/core/theme/app_button_styles.dart';

class AdminGerenciadorPromocoesPage extends StatefulWidget {
  const AdminGerenciadorPromocoesPage({super.key});

  @override
  State<AdminGerenciadorPromocoesPage> createState() => _AdminGerenciadorPromocoesPageState();
}

class _AdminGerenciadorPromocoesPageState extends State<AdminGerenciadorPromocoesPage> {
  final _promotionRepo = SupabasePromotionRepository();
  final _serviceRepo = SupabaseServiceRepository();
  final _packageRepo = SupabasePackageRepository(Supabase.instance.client);
  final _dashboardRepo = SupabaseDashboardRepository();
  final _picker = ImagePicker();
  
  bool _isLoading = true;
  bool _isUploading = false;
  bool _hasChanges = false;
  List<PromotionModel> _promotions = [];
  List<PromotionModel> _editedPromotions = [];
  final Set<String> _pendingDeletions = {};
  List<ServiceModel> _services = [];
  List<PacoteTemplateModel> _packages = [];

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    setState(() => _isLoading = true);
    try {
      final results = await Future.wait<dynamic>([
        _promotionRepo.getAllPromotionsAdmin(),
        _serviceRepo.getActiveServices(),
        _packageRepo.getTemplates(),
      ]);

      setState(() {
        _promotions = results[0] as List<PromotionModel>;
        _editedPromotions = List.from(_promotions);
        _pendingDeletions.clear();
        _hasChanges = false;
        _services = results[1] as List<ServiceModel>;
        _packages = results[2] as List<PacoteTemplateModel>;
        _isLoading = false;
      });
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro ao carregar dados: $e'), backgroundColor: Colors.red),
        );
      }
      setState(() => _isLoading = false);
    }
  }

  void _createNewCard() {
    setState(() {
      _editedPromotions.add(PromotionModel(
        id: '', // Will be generated by UUID on insert
        titulo: 'Nova Promoção',
        subtitulo: 'Descrição curta aqui',
        imagemUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=2070&auto=format&fit=crop',
        ordem: _editedPromotions.length + 1,
        ativo: true,
      ));
      _hasChanges = true;
    });
  }

  void _updateLocalPromotionByIndex(int index, PromotionModel updated) {
    setState(() {
      _editedPromotions[index] = updated;
      _hasChanges = true;
    });
  }

  Future<void> _saveAllChanges() async {
    setState(() => _isLoading = true);
    final adminId = Supabase.instance.client.auth.currentUser?.id;
    
    try {
      // 1. Deletions
      for (final id in _pendingDeletions) {
        // Encontrar o título original para o log
        final originalPromo = _promotions.where((p) => p.id == id).firstOrNull;
        final title = originalPromo?.titulo ?? 'Promoção Desconhecida';
        
        await _promotionRepo.deletePromotion(id);
        
        await _dashboardRepo.logActivity(
          tipo: 'configuracao',
          titulo: 'Promoção Excluída',
          descricao: 'A promoção "$title" foi excluída.',
          userId: adminId,
          metadata: {
            'changes': [
              {'campo': 'Promoção', 'antigo': title, 'novo': 'Excluída'}
            ]
          },
        );
      }

      // 2. Inserts & Updates
      for (final promo in _editedPromotions) {
        if (promo.id.isEmpty) {
          await _promotionRepo.insertPromotion(promo);
          await _dashboardRepo.logActivity(
            tipo: 'configuracao',
            titulo: 'Promoção Criada',
            descricao: 'A promoção "${promo.titulo}" foi criada.',
            userId: adminId,
            metadata: {
              'changes': [
                {'campo': 'Nova Promoção', 'antigo': 'Não existia', 'novo': promo.titulo}
              ]
            },
          );
        } else {
          // Verificar se houve mudança real antes de logar (opcional, mas bom)
          final original = _promotions.where((p) => p.id == promo.id).firstOrNull;
          if (original != null && (original.titulo != promo.titulo || original.ativo != promo.ativo || original.servicoId != promo.servicoId || original.pacoteId != promo.pacoteId)) {
            final changes = <Map<String, String>>[];
            if (original.titulo != promo.titulo) {
              changes.add({'campo': 'Título (${original.titulo})', 'antigo': original.titulo, 'novo': promo.titulo});
            }
            if (original.subtitulo != promo.subtitulo) {
              changes.add({'campo': 'Subtítulo (${promo.titulo})', 'antigo': original.subtitulo, 'novo': promo.subtitulo});
            }
            if (original.ativo != promo.ativo) {
              changes.add({'campo': 'Status (${promo.titulo})', 'antigo': original.ativo ? 'Ativo' : 'Inativo', 'novo': promo.ativo ? 'Ativo' : 'Inativo'});
            }
            if (original.servicoId != promo.servicoId || original.pacoteId != promo.pacoteId) {
               String oldLinked = 'Nenhum';
               if (original.servicoId != null) oldLinked = 'Serviço ID: ${original.servicoId}';
               if (original.pacoteId != null) oldLinked = 'Pacote ID: ${original.pacoteId}';
               
               String newLinked = 'Nenhum';
               if (promo.servicoId != null) newLinked = 'Serviço ID: ${promo.servicoId}';
               if (promo.pacoteId != null) newLinked = 'Pacote ID: ${promo.pacoteId}';
               
               changes.add({'campo': 'Vínculo (${promo.titulo})', 'antigo': oldLinked, 'novo': newLinked});
            }

            await _promotionRepo.updatePromotion(promo);
            await _dashboardRepo.logActivity(
              tipo: 'configuracao',
              titulo: 'Promoção Editada',
              descricao: 'A promoção "${promo.titulo}" foi alterada.',
              userId: adminId,
              metadata: {'changes': changes},
            );
          } else if (original == null) {
             // Caso improvável mas possível se o estado dessincronizar
             await _promotionRepo.updatePromotion(promo);
          }
        }
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Todas as alterações foram salvas!'), backgroundColor: Color(0xFF2D5A46)),
        );
      }
      await _loadData();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro ao salvar tudo: $e'), backgroundColor: Colors.red),
        );
      }
      setState(() => _isLoading = false);
    }
  }

  void _discardChanges() {
    setState(() {
      _editedPromotions = List.from(_promotions);
      _pendingDeletions.clear();
      _hasChanges = false;
    });
  }

  Future<void> _pickAndUploadImage(int index, PromotionModel promo) async {
    try {
      final XFile? image = await _picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 70,
        maxWidth: 1200,
      );

      if (image == null) return;

      setState(() => _isUploading = true);

      final bytes = await image.readAsBytes();
      final url = await _promotionRepo.uploadPromotionImage(image.name, bytes);

      if (url != null) {
        // Update local state instead of saving to repo
        _updateLocalPromotionByIndex(index, promo.copyWith(imagemUrl: url));
        
        // Note: Image deletion from storage still happens immediately as it's a file operation
        if (promo.imagemUrl.isNotEmpty && promo.imagemUrl.contains('supabase')) {
          await _promotionRepo.deletePromotionImage(promo.imagemUrl);
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro no upload: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      setState(() => _isUploading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    const goldColor = Color(0xFFC7A36B);

    return Scaffold(
      backgroundColor: AppColors.background,
      body: _isLoading 
        ? const Center(child: CircularProgressIndicator(color: goldColor))
        : Column(
            children: [
              _buildFilters(AppColors.primary, goldColor),
              Expanded(
                child: RefreshIndicator(
                  onRefresh: _loadData,
                  color: goldColor,
                  child: _buildPromotionsList(AppColors.primary, goldColor),
                ),
              ),
              if (_hasChanges) _buildBottomBar(goldColor),
            ],
          ),
    );
  }

  String _statusFilter = 'Todos';
  String _orderFilter = 'Nenhum';

  Widget _buildFilters(Color primaryGreen, Color goldColor) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
      color: AppColors.background,
      child: Row(
        children: [
          Expanded(
            child: _buildFilterDropdown(
              label: 'Status',
              value: _statusFilter,
              items: ['Todos', 'Ativos', 'Inativos'],
              onChanged: (val) => setState(() => _statusFilter = val!),
              goldColor: goldColor,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: _buildFilterDropdown(
              label: 'Ordenar',
              value: _orderFilter,
              items: ['Nenhum', 'Título', 'Ordem'],
              onChanged: (val) => setState(() => _orderFilter = val!),
              goldColor: goldColor,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFilterDropdown({
    required String label,
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
    required Color goldColor,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(fontSize: 10,
            fontWeight: FontWeight.bold,
            color: goldColor,
            letterSpacing: 1.2,
          ),
        ),
        const SizedBox(height: 4),
        Container(
          height: 40,
          padding: const EdgeInsets.symmetric(horizontal: 12),
          decoration: BoxDecoration(
            color: const Color(0xFFF8FBF9),
            borderRadius: BorderRadius.circular(10),
            border: Border.all(color: goldColor.withOpacity(0.2)),
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<String>(
              value: value,
              isExpanded: true,
              icon: Icon(Icons.keyboard_arrow_down, color: goldColor, size: 18),
              style: TextStyle(color: const Color(0xFF2D5A46),
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
              items: items.map((String item) {
                return DropdownMenuItem<String>(
                  value: item,
                  child: Text(item),
                );
              }).toList(),
              onChanged: onChanged,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildPromotionsList(Color primaryGreen, Color goldColor) {
    List<PromotionModel> filtered = List.from(_editedPromotions); // Use local state

    // Apply Status Filter
    if (_statusFilter == 'Ativos') {
      filtered = filtered.where((p) => p.ativo).toList();
    } else if (_statusFilter == 'Inativos') {
      filtered = filtered.where((p) => !p.ativo).toList();
    }

    // Apply Order Filter
    if (_orderFilter == 'Título') {
      filtered.sort((a, b) => a.titulo.compareTo(b.titulo));
    } else if (_orderFilter == 'Ordem') {
      filtered.sort((a, b) => a.ordem.compareTo(b.ordem));
    }

    return ListView(
      padding: const EdgeInsets.all(24),
      children: [
        ...filtered.asMap().entries.map((entry) {
          // Find the original index in _editedPromotions to ensure we update the right one
          final realIndex = _editedPromotions.indexOf(entry.value);
          return _buildPromotionEditorCard(realIndex, entry.value, primaryGreen, goldColor);
        }),
        const SizedBox(height: 12),
        Center(
          child: TextButton.icon(
            onPressed: _createNewCard,
            icon: Icon(Icons.add_circle_outline, color: goldColor),
            label: Text(
              'Criar novo card',
              style: TextStyle(color: goldColor,
                fontWeight: FontWeight.bold,
                letterSpacing: 1.2,
              ),
            ),
            style: TextButton.styleFrom(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            ),
          ),
        ),
        const SizedBox(height: 40),
      ],
    );
  }

  Widget _buildPromotionEditorCard(int index, PromotionModel promo, Color primaryGreen, Color goldColor) {
    return Container(
      margin: const EdgeInsets.only(bottom: 24),
      padding: const EdgeInsets.all(20),
      // ... same styling ...
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
        border: Border.all(color: goldColor.withOpacity(0.1)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (_isUploading)
            const LinearProgressIndicator(color: Color(0xFFC7A36B)),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Card #${index + 1}',
                style: TextStyle(
                  fontFamily: 'Playfair Display',
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: primaryGreen,
                ),
              ),
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.delete_outline, color: Colors.redAccent, size: 20),
                    onPressed: () => _confirmDeleteLocal(index, promo),
                  ),
                  Switch(
                    value: promo.ativo,
                    activeThumbColor: primaryGreen,
                    onChanged: (val) => _updateLocalPromotionByIndex(index, promo.copyWith(ativo: val)),
                  ),
                ],
              ),
            ],
          ),
          const Divider(),
          const SizedBox(height: 12),
          _buildField(
            label: 'Título',
            initialValue: promo.titulo,
            onChanged: (val) => _updateLocalPromotionByIndex(index, promo.copyWith(titulo: val)),
          ),
          const SizedBox(height: 16),
          _buildField(
            label: 'Subtítulo',
            initialValue: promo.subtitulo,
            onChanged: (val) => _updateLocalPromotionByIndex(index, promo.copyWith(subtitulo: val)),
          ),
          _buildImageSection(index, promo, primaryGreen, goldColor),
          const SizedBox(height: 16),
          _buildServiceDropdown(index, promo, primaryGreen, goldColor),
        ],
      ),
    );
  }

  Future<void> _confirmDeleteLocal(int index, PromotionModel promo) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Excluir card', style: TextStyle(fontWeight: FontWeight.bold)),
        content: const Text('Tem certeza que deseja excluir esta promoção? As alterações serão definitivas ao salvar.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            style: AppButtonStyles.cancelButtonStyle(),
            child: Text('Cancelar', style: AppButtonStyles.cancelTextStyle()),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: AppButtonStyles.small(foregroundColor: Colors.red),
            child: const Text('Excluir'),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      setState(() {
        if (promo.id.isNotEmpty) {
          _pendingDeletions.add(promo.id);
        }
        _editedPromotions.removeAt(index);
        _hasChanges = true;
      });
    }
  }

  Widget _buildImageSection(int index, PromotionModel promo, Color primaryGreen, Color goldColor) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Imagem da promoção',
          style: TextStyle(fontSize: 10,
            fontWeight: FontWeight.bold,
            color: const Color(0xFF6E8F7B).withOpacity(0.8),
            letterSpacing: 1.2,
          ),
        ),
        const SizedBox(height: 12),
        if (promo.imagemUrl.isNotEmpty)
          Container(
            height: 120,
            width: double.infinity,
            margin: const EdgeInsets.only(bottom: 12),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              image: DecorationImage(
                image: NetworkImage(promo.imagemUrl),
                fit: BoxFit.cover,
              ),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.1),
                  blurRadius: 10,
                  offset: const Offset(0, 4),
                ),
              ],
            ),
            child: Align(
              alignment: Alignment.topRight,
              child: IconButton(
                icon: const CircleAvatar(
                  backgroundColor: Colors.white,
                  child: Icon(Icons.close, color: Colors.red, size: 18),
                ),
                onPressed: () {
                  _updateLocalPromotionByIndex(index, promo.copyWith(imagemUrl: ''));
                },
              ),
            ),
          ),
        Row(
          children: [
            Expanded(
              child: _buildField(
                label: 'URL da imagem',
                initialValue: promo.imagemUrl,
                hint: 'Cole o link da imagem aqui...',
                onChanged: (val) => _updateLocalPromotionByIndex(index, promo.copyWith(imagemUrl: val)),
              ),
            ),
            const SizedBox(width: 12),
            Column(
              children: [
                const SizedBox(height: 20), // Alinhar com o campo de texto
                Container(
                  decoration: BoxDecoration(
                    color: goldColor,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: IconButton(
                    icon: const Icon(Icons.photo_library, color: Colors.white),
                    onPressed: () => _pickAndUploadImage(index, promo),
                    tooltip: 'Carregar Arquivo',
                  ),
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildField({
    required String label,
    required String initialValue,
    required Function(String) onChanged,
    String? hint,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(fontSize: 10,
            fontWeight: FontWeight.bold,
            color: const Color(0xFF6E8F7B).withOpacity(0.8),
            letterSpacing: 1.2,
          ),
        ),
        const SizedBox(height: 8),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.03),
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: TextFormField(
            initialValue: initialValue,
            onChanged: onChanged,
            style: TextStyle(fontSize: 14,
              fontWeight: FontWeight.w500,
              color: const Color(0xFF1A1A1A),
            ),
            decoration: InputDecoration(
              hintText: hint,
              hintStyle: TextStyle(color: Colors.black26,
                fontSize: 13,
              ),
              isDense: true,
              contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(
                  color: Colors.black.withOpacity(0.05),
                  width: 1.5,
                ),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(
                  color: const Color(0xFFC7A36B),
                  width: 1.5,
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildServiceDropdown(int index, PromotionModel promo, Color primaryGreen, Color goldColor) {
    String currentLinkedName = 'Nenhum vínculo';
    if (promo.servicoId != null) {
      final s = _services.where((s) => s.id == promo.servicoId).firstOrNull;
      currentLinkedName = s?.nome ?? 'Serviço não encontrado';
    } else if (promo.pacoteId != null) {
      final p = _packages.where((p) => p.id == promo.pacoteId).firstOrNull;
      currentLinkedName = p?.titulo != null ? 'PACOTE: ${p!.titulo}' : 'Pacote não encontrado';
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Vincular a um Procedimento ou Pacote',
          style: TextStyle(fontSize: 10,
            fontWeight: FontWeight.bold,
            color: const Color(0xFF6E8F7B),
            letterSpacing: 1.2,
          ),
        ),
        const SizedBox(height: 8),
        InkWell(
          onTap: () => _showLinkingModal(index, promo, primaryGreen, goldColor),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.black.withOpacity(0.08)),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.02),
                  blurRadius: 10,
                  offset: const Offset(0, 4),
                ),
              ],
            ),
            child: Row(
              children: [
                Icon(
                  promo.pacoteId != null ? Icons.inventory_2_outlined : Icons.spa_outlined,
                  color: goldColor,
                  size: 20,
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    currentLinkedName,
                    style: TextStyle(fontSize: 14,
                      fontWeight: FontWeight.w500,
                      color: (promo.servicoId == null && promo.pacoteId == null)
                          ? Colors.black38 
                          : const Color(0xFF1A1A1A),
                    ),
                  ),
                ),
                Icon(Icons.keyboard_arrow_down, color: goldColor.withOpacity(0.5)),
              ],
            ),
          ),
        ),
      ],
    );
  }

  void _showLinkingModal(int index, PromotionModel promo, Color primaryGreen, Color goldColor) {
    String searchQuery = '';

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setModalState) {
            final filteredServices = _services.where((s) => 
              s.nome.toLowerCase().contains(searchQuery.toLowerCase())
            ).toList();
            final filteredPackages = _packages.where((p) => 
              p.titulo.toLowerCase().contains(searchQuery.toLowerCase())
            ).toList();

            return Container(
              height: MediaQuery.of(context).size.height * 0.85,
              decoration: const BoxDecoration(
                color: Color(0xFFF8FBF9),
                borderRadius: BorderRadius.vertical(top: Radius.circular(30)),
              ),
              child: Column(
                children: [
                  const SizedBox(height: 12),
                  Container(
                    width: 40,
                    height: 4,
                    decoration: BoxDecoration(
                      color: Colors.black12,
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(24, 24, 24, 16),
                    child: Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Vincular promoção',
                                style: TextStyle(fontFamily: 'Playfair Display', 
                                  fontSize: 24,
                                  fontWeight: FontWeight.bold,
                                  color: primaryGreen,
                                ),
                              ),
                              Text(
                                'Selecione um item para vincular ao banner',
                                style: TextStyle(fontSize: 13,
                                  color: Colors.black45,
                                ),
                              ),
                            ],
                          ),
                        ),
                        IconButton(
                          onPressed: () => Navigator.pop(context),
                          icon: const Icon(Icons.close),
                        ),
                      ],
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
                    child: TextField(
                      onChanged: (val) {
                        setModalState(() {
                          searchQuery = val;
                        });
                      },
                      decoration: InputDecoration(
                        hintText: 'Buscar procedimentos ou pacotes...',
                        prefixIcon: const Icon(Icons.search, size: 20),
                        filled: true,
                        fillColor: Colors.white,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(15),
                          borderSide: BorderSide(color: Colors.black.withOpacity(0.05)),
                        ),
                        contentPadding: const EdgeInsets.symmetric(vertical: 0),
                      ),
                    ),
                  ),
                  Expanded(
                    child: ListView(
                      padding: const EdgeInsets.symmetric(horizontal: 24),
                      children: [
                        const SizedBox(height: 12),
                        _buildModalItem(
                          icon: Icons.link_off,
                          title: 'Remover vínculo atual',
                          onTap: () {
                            _updateLocalPromotionByIndex(index, promo.copyWith(clearServico: true, clearPacote: true));
                            Navigator.pop(context);
                          },
                          color: Colors.red.withOpacity(0.7),
                        ),
                        const SizedBox(height: 24),
                        
                        _buildModalSectionHeader('Procedimentos', goldColor),
                        if (filteredServices.isEmpty)
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 20),
                            child: Text(
                              'Nenhum procedimento encontrado',
                              textAlign: TextAlign.center,
                              style: TextStyle(color: Colors.black38, fontSize: 13),
                            ),
                          ),
                        ...filteredServices.map((s) => _buildModalItem(
                          icon: Icons.spa_outlined,
                          title: s.nome,
                          isSelected: promo.servicoId == s.id,
                          goldColor: goldColor,
                          onTap: () {
                            _updateLocalPromotionByIndex(index, promo.copyWith(servicoId: s.id, clearPacote: true));
                            Navigator.pop(context);
                          },
                        )),
                        
                        const SizedBox(height: 32),
                        _buildModalSectionHeader('Pacotes', goldColor),
                        if (filteredPackages.isEmpty)
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 20),
                            child: Text(
                              'Nenhum pacote encontrado',
                              textAlign: TextAlign.center,
                              style: TextStyle(color: Colors.black38, fontSize: 13),
                            ),
                          ),
                        ...filteredPackages.map((p) => _buildModalItem(
                          icon: Icons.inventory_2_outlined,
                          title: p.titulo,
                          isSelected: promo.pacoteId == p.id,
                          goldColor: goldColor,
                          onTap: () {
                            _updateLocalPromotionByIndex(index, promo.copyWith(pacoteId: p.id, clearServico: true));
                            Navigator.pop(context);
                          },
                        )),
                        const SizedBox(height: 50),
                      ],
                    ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  Widget _buildModalSectionHeader(String title, Color goldColor) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12, left: 4),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: BoxDecoration(
              color: goldColor.withOpacity(0.1),
              borderRadius: BorderRadius.circular(6),
            ),
            child: Text(
              title,
              style: TextStyle(fontSize: 11,
                fontWeight: FontWeight.bold,
                color: goldColor,
                letterSpacing: 1.2,
              ),
            ),
          ),
          const SizedBox(width: 8),
          Expanded(child: Divider(color: goldColor.withOpacity(0.1))),
        ],
      ),
    );
  }

  Widget _buildModalItem({
    required IconData icon,
    required String title,
    required VoidCallback onTap,
    bool isSelected = false,
    Color? color,
    Color? goldColor,
  }) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        onTap: onTap,
        dense: true,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        tileColor: isSelected ? (goldColor ?? const Color(0xFFC7A36B)).withOpacity(0.05) : null,
        leading: Icon(icon, color: color ?? (isSelected ? goldColor : Colors.black45), size: 18),
        title: Text(
          title,
          style: TextStyle(fontSize: 14,
            fontWeight: isSelected ? FontWeight.bold : FontWeight.w500,
            color: isSelected ? (goldColor ?? const Color(0xFFC7A36B)) : Colors.black87,
          ),
        ),
        trailing: isSelected ? Icon(Icons.check_circle, color: goldColor, size: 20) : null,
      ),
    );
  }

  Widget _buildBottomBar(Color goldColor) {
    return Container(
      padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 20,
            offset: const Offset(0, -5),
          ),
        ],
      ),
      child: Row(
        children: [
          Expanded(
            child: TextButton(
              onPressed: _discardChanges,
              style: AppButtonStyles.cancelButtonStyle(),
              child: Text(
                'Cancelar',
                style: AppButtonStyles.cancelTextStyle(),
              ),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            flex: 2,
            child: ElevatedButton(
              onPressed: _saveAllChanges,
              style: AppButtonStyles.primary(),
              child: Center(
                child: Text(
                  'Salvar alterações',
                  style: TextStyle(fontWeight: FontWeight.bold,
                    letterSpacing: 1.0,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

